name: Validate JSON

on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        run: |
          if jq . apps.json; then echo 'Valid JSON!'; else echo 'Invalid JSON!'; exit 1; fi
